# Generated by Django 5.2 on 2025-04-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tran_id', models.AutoField(primary_key=True, serialize=False)),
                ('tran_mode', models.CharField(choices=[('UPI', 'UPI'), ('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('tran_time', models.DateTimeField()),
                ('tran_status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], max_length=10)),
                ('tran_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
