# Generated by Django 5.2 on 2025-05-02 09:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_appointmentcharge_labtestcharge_labtest_priority_and_more'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('invoice_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_type_name', models.CharField(max_length=100)),
                ('invoice_type_remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('payment_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(max_length=100)),
                ('payment_method_remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transaction_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type_name', models.CharField(max_length=100)),
                ('transaction_type_remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_symbol', models.CharField(max_length=10)),
                ('unit_remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tran_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tran_remarks',
            new_name='transaction_remark',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tran_mode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tran_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tran_time',
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='hospital.patient'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_details',
            field=models.JSONField(blank=True, help_text='Additional payment details', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.paymentmethod'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.transactiontype'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_datetime', models.DateTimeField(auto_now_add=True)),
                ('invoice_items', models.JSONField(help_text='List of charge IDs')),
                ('invoice_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('invoice_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hospital.patient')),
                ('tran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='transactions.transaction')),
                ('invoice_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='transactions.invoicetype')),
                ('invoice_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='transactions.unit')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.unit'),
        ),
    ]
