# Generated by Django 5.2 on 2025-05-02 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_appointmentcharge_charge_unit_and_more'),
        ('transactions', '0002_invoicetype_paymentmethod_transactiontype_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='hospital.patient'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.transactiontype'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.unit'),
        ),
    ]
