# Generated by Django 5.2 on 2025-04-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('staff', 'Staff')], default='patient', max_length=10),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='emailotp',
            unique_together={('email', 'user_type')},
        ),
    ]
