# Generated by Django 5.2 on 2025-04-22 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=255)),
                ('staff_joining_date', models.DateField()),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorType',
            fields=[
                ('doctor_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_mobile', models.CharField(max_length=20)),
                ('patient_remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('role_permissions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='LabTechnicianDetails',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lab_tech_details', serialize=False, to='hospital.staff')),
                ('certification', models.CharField(max_length=255)),
                ('lab_experience_years', models.IntegerField()),
                ('assigned_lab', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorConsultationHours',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_hours', to='hospital.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_dob', models.DateField()),
                ('patient_gender', models.BooleanField()),
                ('patient_blood_group', models.CharField(max_length=5)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_height', models.FloatField()),
                ('patient_weight', models.FloatField()),
                ('patient_heartrate', models.IntegerField()),
                ('patient_spo2', models.FloatField()),
                ('patient_temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='hospital.patient')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hospital.role'),
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_dob', models.DateField()),
                ('staff_address', models.TextField()),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_details', to='hospital.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor_details', serialize=False, to='hospital.staff')),
                ('doctor_specialization', models.CharField(max_length=255)),
                ('doctor_license', models.CharField(max_length=255)),
                ('doctor_experience_years', models.IntegerField()),
                ('doctor_qualification', models.CharField(max_length=255)),
                ('doctor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_details', to='hospital.doctortype')),
            ],
        ),
    ]
