# Generated by Django 5.2 on 2025-04-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
        migrations.AddField(
            model_name='labtechniciandetails',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='lab_tech_photos/'),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
