# Generated by Django 5.2 on 2025-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
