# Generated by Django 5.2 on 2025-04-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_patient_is_authenticated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
