# Generated by Django 5.2 on 2025-04-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_patient_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
