# Generated by Django 5.2 on 2025-04-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_staff_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortype',
            name='doctor_type_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
