# Generated by Django 5.2 on 2025-04-25 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_lab_labtestcategory_labtype_medicine_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='hospital.slot'),
        ),
    ]
