# Generated by Django 5.2 on 2025-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_appointment_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
