# Generated by Django 5.2 on 2025-05-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_appointment_reason_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCharge',
            fields=[
                ('appointment_charge_id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_remark', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestCharge',
            fields=[
                ('test_charge_id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charge_remark', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='labtest',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_test_images/'),
        ),
        migrations.AddField(
            model_name='labtesttype',
            name='image_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtesttype',
            name='test_schema',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
