# Generated by Django 5.2 on 2025-05-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_appointmentrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='status',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('paid', 'Paid'), ('completed', 'Completed'), ('missed', 'Missed'), ('failed', 'Failed')], default='recommended', max_length=15),
        ),
    ]
