# Generated by Django 4.2.17 on 2025-08-21 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0014_labtest_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientHistoryDocs",
            fields=[
                ("doc_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("lab_report", "Lab Report"),
                            ("prescription", "Prescription"),
                            ("discharge_summary", "Discharge Summary"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document_name",
                    models.CharField(help_text="Original file name", max_length=255),
                ),
                (
                    "document_url",
                    models.URLField(help_text="Path to uploaded document"),
                ),
                (
                    "document_processed",
                    models.BooleanField(
                        default=False, help_text="Indicates if OCR completed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document_remarks",
                    models.CharField(
                        blank=True,
                        help_text="Any comments about processing or document issues",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_documents",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient History Document",
                "verbose_name_plural": "Patient History Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.JSONField(
                        default=dict,
                        help_text="Extracted structured patient medical history (diseases, conditions, treatments, etc.)",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        default=list, help_text="Extracted allergies if mentioned"
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        default=list,
                        help_text="Extracted doctor/medical notes or unstructured text",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_history",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient History",
                "verbose_name_plural": "Patient Histories",
            },
        ),
    ]
